# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.IntegerField()),
                ('day_linked', models.IntegerField()),
                ('source_price', models.FloatField()),
                ('price', models.FloatField()),
                ('enabled', models.BooleanField(default=True)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
